name: CI Release
on:
  push:
    branches:
      - main
      - blizzard
  workflow_dispatch:

jobs:
    release:
        runs-on: ubuntu-latest
        name: Semantic Release

        steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Set up Golang 1.23
          uses: actions/setup-go@v5
          with:
           go-version: 1.23
        
        - name: Release
          uses: go-semantic-release/action@v1
          with:
            prerelease: ${{ github.ref_name != 'main' }}
            changelog-generator-opt: "emojis=true"
            hooks: goreleaser

          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}